export const ALL_PERMISSIONS = {
    Device: ['DEVICE_CREATE', 'DEVICE_READ', 'DEVICE_UPDATE', 'DEVICE_DELETE'],
    Employee: ['EMPLOYEE_CREATE', 'EMPLOYEE_READ', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE'],
    Branch: ['BRANCH_CREATE', 'BRANCH_READ', 'BRANCH_UPDATE', 'BRANCH_DELETE'],
    Department: ['DEPARTMENT_CREATE', 'DEPARTMENT_READ', 'DEPARTMENT_UPDATE', 'DEPARTMENT_DELETE'],
    Assignment: ['ASSIGNMENT_CREATE', 'ASSIGNMENT_READ'],
    'Repair Request': ['REPAIR_REQUEST_CREATE', 'REPAIR_REQUEST_READ', 'REPAIR_REQUEST_UPDATE'],
    Report: ['REPORT_READ'],
    User: ['USER_CREATE', 'USER_READ', 'USER_UPDATE', 'USER_DELETE'],
    Role: ['ROLE_CREATE', 'ROLE_READ', 'ROLE_UPDATE', 'ROLE_DELETE'],
}

export const ALL_PERMS_FLAT = Object.values(ALL_PERMISSIONS).flat()
